### ISSUE TITLE
List inputs in README in a table format

### ISSUE THREAD

**Issue by iamazeem** [Mudlet/gsheets-append-action#21]
Please add the list of `inputs` in the README in a table format.

The table generation can be automated with [`yq`](https://mikefarah.gitbook.io/yq/):

```shell
$ cat action.yml | yq -r '.inputs | keys[] as $k | "| `\($k)` | \(.[$k].description) |"'
| `DATA_ENV_NAME` | The environment variable containing the data to upload in CSV format. |
| `GOOGLE_USER_KEY` | The users private key to authenticate the service account user. |
| `GOOGLE_USER_MAIL` | The user ID to authenticate the service account user. |
| `SPREADSHEET` | The spreadsheet ID to append the data to. |
| `TABLE_START_CELL` | The cell that defines the "table anchor" in the format `sheetName!A1`. |
| `UPDATE` | Update or append data. |
```

The generated table would look like this:

| Input | Description |
|--------|-----------------|
| `DATA_ENV_NAME` | The environment variable containing the data to upload in CSV format. |
| `GOOGLE_USER_KEY` | The users private key to authenticate the service account user. |
| `GOOGLE_USER_MAIL` | The user ID to authenticate the service account user. |
| `SPREADSHEET` | The spreadsheet ID to append the data to. |
| `TABLE_START_CELL` | The cell that defines the "table anchor" in the format `sheetName!A1`. |
| `UPDATE` | Update or append data. |

This can further be refined to add `required` and `default` columns.

**Comment by vadi2** [comment]
That looks great - do you want to submit that as a PR given you've already done the work?

**Comment by iamazeem** [comment]
Sure. I'll try to submit a PR for this soon.

**Comment by iamazeem** [comment]
@vadi2 : Please review #24. Thanks!

Used this `yq` command to generate table:

```shell
$ cat action.yml | yq -r '.inputs | keys_unsorted[] as $k | "| `\($k)` | \(.[$k].required // "false") | \(.[$k].default // "") | \(.[$k].description) |"'
| `GOOGLE_USER_MAIL` | true |  | The user ID to authenticate the service account user. |
| `GOOGLE_USER_KEY` | true |  | The users private key to authenticate the service account user. |
| `SPREADSHEET` | true |  | The spreadsheet ID to append the data to. |
| `DATA_ENV_NAME` | true |  | The environment variable containing the data to upload in CSV format. |
| `TABLE_START_CELL` | false | A1 | The cell that defines the "table anchor" in the format `sheetName!A1`. |
| `UPDATE` | false |  | Update or append data. |
```
