### ISSUE TITLE
[Feature Request] Add support for a CSV file e.g. DATA_FILE_PATH

### ISSUE THREAD

**Issue by iamazeem** [Mudlet/gsheets-append-action#22]
Similar to `DATA_ENV_NAME`:

https://github.com/Mudlet/gsheets-append-action/blob/9e575660cb6b4ebcb2685db5293ddf580070a4f8/action.yml#L13-L15

please add support to upload data from a CSV file e.g. via the `DATA_FILE_PATH` input parameter.

With this addition, users will be able to upload more data compared to [what is allowed by the GHA env vars](https://docs.github.com/en/actions/learn-github-actions/variables#limits-for-configuration-variables).

**Comment by keneanung** [comment]
@iamazeem please have a look at #26 whether this fixes the issue for you.
